//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_ClassRoutine_Days
    {
        public int ID { get; set; }
        public Nullable<int> ClassRoutineID { get; set; }
        public Nullable<int> DaysID { get; set; }
    }
}
