//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_CourseStudents
    {
        public int ID { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<decimal> DecidedFee { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<byte> Duration { get; set; }
    }
}
