//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_Courses
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Duration { get; set; }
        public Nullable<decimal> StandardFee { get; set; }
        public Nullable<int> Operator_id { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
    }
}
