//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentColor
    {
        public int ID { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public string ColorMeaning { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
