//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentArea
    {
        public int ID { get; set; }
        public Nullable<int> AssessmentCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_SummaryField { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
