//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSecurityWithDraw
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> SecurityWithdrawnByUser { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<int> WithDrawOperatorID { get; set; }
        public Nullable<decimal> WithDrawAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SalaryMonthID { get; set; }
        public Nullable<int> RefundableTypeID { get; set; }
    }
}
