//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams_Grade
    {
        public int ID { get; set; }
        public Nullable<int> Percentage_from { get; set; }
        public Nullable<int> Percentage_to { get; set; }
        public string Grade_letters { get; set; }
        public Nullable<int> Level_id { get; set; }
    }
}
