//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams_DateSheet_Names
    {
        public int ID { get; set; }
        public Nullable<int> Exam_id { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
    }
}
