//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAmount_History
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ActionUserID { get; set; }
        public Nullable<int> ExpenseAmountID { get; set; }
        public Nullable<decimal> AmountFrom { get; set; }
        public Nullable<decimal> AmountTo { get; set; }
        public Nullable<int> ExpenseHeadID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> T_Date { get; set; }
        public Nullable<int> SalaryMonthID { get; set; }
        public string Remarks { get; set; }
        public string ExpenseTitle { get; set; }
    }
}
