//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeReceipt
    {
        public int ID { get; set; }
        public Nullable<int> StudentPaymentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public string FeeMonth { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<int> ChallanNo { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<System.DateTime> T_Date { get; set; }
        public string PaidType { get; set; }
    }
}
