//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FingerPrint
    {
        public int ID { get; set; }
        public Nullable<byte> AccountType { get; set; }
        public Nullable<byte> Status { get; set; }
        public string FingerPrint1 { get; set; }
        public Nullable<int> AccountID { get; set; }
    }
}
