//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labels_Internal
    {
        public int ID { get; set; }
        public string Default_Singular { get; set; }
        public string Default_Plural { get; set; }
        public string Custom_Singular { get; set; }
        public string Custom_Plural { get; set; }
        public Nullable<bool> UseDefault { get; set; }
        public string Description { get; set; }
    }
}
