//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryReceipt
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> SalaryMonthID { get; set; }
        public Nullable<decimal> TotalReceived { get; set; }
        public Nullable<decimal> TotalReceivable { get; set; }
        public Nullable<decimal> ReceivedAsSalary { get; set; }
    }
}
