//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryReceiptDetail
    {
        public int ID { get; set; }
        public Nullable<int> SalaryReceiptID { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> EmployeePaymentID { get; set; }
        public Nullable<int> EmployeeLoanID { get; set; }
        public Nullable<byte> T_Type { get; set; }
        public Nullable<System.DateTime> T_Date { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
