//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryIncrement
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public Nullable<decimal> IncrementAmount { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<int> SalaryMonthID { get; set; }
        public Nullable<int> AllowanceAmountID { get; set; }
    }
}
