//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityFee
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> SecurityWithdrawnByStudent { get; set; }
        public Nullable<System.DateTime> SecurityWithdrawDate { get; set; }
        public Nullable<int> WithdrawByUserID { get; set; }
        public Nullable<int> PersonalizedFeeID { get; set; }
    }
}
