//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Networks
    {
        public int ID { get; set; }
        public string MobileNetwork { get; set; }
        public string SimNo { get; set; }
        public Nullable<int> PerMinutesSMS { get; set; }
        public Nullable<int> PerDaySMS { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<byte> Priority { get; set; }
        public string ComPort { get; set; }
        public Nullable<long> BaudRate { get; set; }
        public Nullable<int> DataBits { get; set; }
        public string StopBits { get; set; }
        public string ParityBits { get; set; }
        public Nullable<int> WriteTimeout { get; set; }
        public Nullable<int> ReadTimeout { get; set; }
        public Nullable<long> PerSmsDelay { get; set; }
    }
}
