//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Queue
    {
        public int ID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<int> RecipientID { get; set; }
        public Nullable<byte> RecipientType { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> QueuedTime { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> NetworkID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> AttendanceID { get; set; }
        public Nullable<int> EventID { get; set; }
    }
}
