//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Family
    {
        public int ID { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> FatherOccupationID { get; set; }
        public Nullable<int> MotherOccupationID { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string FatherCNIC { get; set; }
        public string MotherCNIC { get; set; }
    }
}
