//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string RollNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string StuCNIC { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<int> JoiningClassID { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string registration_no { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string Email { get; set; }
        public Nullable<int> StuGroupID { get; set; }
    }
}
