//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_temp
    {
        public int ID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int RollNo { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> sDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public byte[] image { get; set; }
    }
}
