//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RegisterStudent
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Class { get; set; }
        public string Section { get; set; }
        public string Status { get; set; }
        public string DateOfAdmission { get; set; }
    }
}
