//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Models.DropDowns
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Gender
    {
        public int Gender_ID { get; set; }
        public string G_Name { get; set; }
    }
}
