//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTech.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams_GroupCollections
    {
        public int ID { get; set; }
        public Nullable<int> Group_id { get; set; }
        public Nullable<int> Exam_id { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string SequenceNumber { get; set; }
    }
}
